# Configure Netlify builds.
# build:
#   publish: "dist/"
#   command: "pnpm run build"
# # Request bots not to index the admin section.
# headers:
#   for: "/admin/*"
#   headers.values:
#     X-Robots-Tag: "noindex"

backend:
  name: github
  branch: main # change this to your branch
  repo: PhireLulea/hemsida # change this to your repo
  site_domain: hemsida-one.vercel.app # change this to your domain
  base_url: https://hemsida-one.vercel.app # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: "public/assets"
public_folder: "assets"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
